### ISSUE TITLE
Can't install extension using chrome on mac Version 58.0.3029.110 (64-bit)

### ISSUE THREAD

**Issue by savvasmad** [orschiro/tsrlt-chrome-extension#14] opened 2017-06-05 07:33 UTC
Hello!
By some reason, i can't install the extension on Chrome 58.0.3029.110 (64-bit) on mac.
Any suggestions?
Thanks

**Comment by orschiro** [comment] 2017-06-05 09:51
Dear @savvasmad,

Please help me as I am not on a Mac. 

Do you get any errors?

I am off for a week. My response to this may be delayed. 

Please apologise!

Yours,

Robert

**Comment by savvasmad** [comment] 2017-06-05 09:53
I don't even have an install button.
Please take a look at the screenshot

<img width="989" alt="screen shot 2017-06-05 at 12 52 19 pm" src="https://cloud.githubusercontent.com/assets/29193564/26779420/f1f9c7ea-49ed-11e7-8b8f-9b59443d806f.png">

**Comment by orschiro** [comment] 2017-06-05 10:01
From which country are you accessing this page?

Can you please try a proxy?

**Comment by savvasmad** [comment] 2017-06-05 10:04
I am from Latvia
Will try proxy and let you know the result.

**Comment by orschiro** [comment] 2017-06-05 10:07
Thank you!

**Comment by orschiro** [comment] 2017-06-05 10:22
I hope you can get it to work with a Chrome proxy extension. 

If not, I will be back in a few days. 

Thanks for reporting this problem!

Yours,

Robert

**Comment by orschiro** [comment] 2017-06-06 13:48
@savvasmad did it work?

**Comment by orschiro** [comment] 2017-06-07 07:49
I am closing this issue under the assumption that using a Proxy server did work.

**Closed by orschiro** 2017-06-07 07:49 UTC

**Comment by savvasmad** [comment] 2017-06-07 11:46
No, it didn't work so i decided to use another similar extension. Thanks anyways

**Comment by orschiro** [comment] 2017-06-12 11:54
You are welcome.

**Comment by ureimers** [comment] 2017-07-29 08:00
Is it correct, that the extension now costs 0.74€?

I'm accessing the store from Germany.

**Comment by orschiro** [comment] 2017-07-29 11:40
@ureimers you can get the extension for free from here:

https://github.com/orschiro/tsrlt-chrome-extension/releases

:-)

**Comment by ureimers** [comment] 2017-08-01 09:33
@orschiro Yes, that's why I was wondering why I suddenly should pay for it. My Chrome (v60) extension store first wanted me to login and then asked me to pay 0.74€. I tested this on my private PC and from the one form my working place.

Here are some screenshots I took just now:
![switch tabs extension - login](https://user-images.githubusercontent.com/1671217/28818966-faee39a8-76ac-11e7-8c75-cee3ccf05c38.jpg)
![switch tabs extension - pay](https://user-images.githubusercontent.com/1671217/28818969-fd314f34-76ac-11e7-8be3-706fc0f2bb9d.jpg)

Installing an extension without the store keeps bugging me about the fact that I have my developer mode enabled (which I need to do in order to manually install an extension).

Cheers

**Comment by orschiro** [comment] 2017-08-01 13:31
@ureimers I put it for paid payments to raise money to donate to other open source projects. Hence, you are free to not pay if you choose the version from Github.

**Comment by ureimers** [comment] 2017-08-02 10:07
That's totally fine.

I just wasn't aware of that and wanted to ask if the payment option was intended, an error, or maybe even some scammer/phisher.

**Comment by orschiro** [comment] 2017-08-02 10:15
@ureimers I will make this more clear on the webstore page how the payments are used. Thanks!
